"use client";

import { useEffect, useState } from "react";
import { Activity, AlertTriangle, Bot, CheckCircle2, ChevronRight, CircleDot, FileCheck2, GitPullRequest, Search, Settings2, ShieldCheck, TestTube2, Workflow } from "lucide-react";

const prs = [
  { icon: CheckCircle2, color: "green", title: "Add rate-limit handling to payments API", meta: "#1842 · payments-service · Riya S.", status: "Verified", detail: "All evidence checks passed" },
  { icon: AlertTriangle, color: "yellow", title: "Refactor customer event pipeline", meta: "#1839 · event-stream · Arjun K.", status: "2 checks missing", detail: "Tests and rollback plan" },
  { icon: AlertTriangle, color: "red", title: "Update auth token refresh flow", meta: "#1832 · identity-service · Neha P.", status: "Decision conflict", detail: "Conflicts with AUTH-17" },
];

export default function Home() {
  const [active, setActive] = useState("Overview");
  const [filter, setFilter] = useState("All");
  const [message, setMessage] = useState("");
  const [running, setRunning] = useState(false);
  const [apiConnected, setApiConnected] = useState<boolean | null>(null);
  const [authState, setAuthState] = useState<"loading" | "authenticated" | "anonymous">("loading");
  const [selectedPr, setSelectedPr] = useState<(typeof prs)[number] | null>(null);
  useEffect(() => {
    fetch("/api/dashboard")
      .then(response => { if (!response.ok) throw new Error("API unavailable"); return response.json(); })
      .then(() => setApiConnected(true))
      .catch(() => setApiConnected(false));
    fetch("/api/auth/me")
      .then(response => response.json())
      .then(user => setAuthState(user.authenticated ? "authenticated" : "anonymous"))
      .catch(() => setAuthState("anonymous"));
  }, []);
  const notify = (text: string) => { setMessage(text); window.setTimeout(() => setMessage(""), 2600); };
  const runVerification = () => { setRunning(true); fetch("/api/verification/run", { method: "POST" }).then(response => { if (!response.ok) throw new Error("Verification failed"); return response.json(); }).then(result => notify(result.message)).catch(() => notify("The verification service is unavailable")).finally(() => setRunning(false)); };

  return <div className="shell">
    <aside className="sidebar"><div className="brand"><span className="logo">D</span> DevContext</div><div className="label">Workspace</div><nav>{["Overview", "Pull requests", "Decisions", "Incidents", "Integrations"].map((item, index) => <button key={item} className={active === item ? "nav active" : "nav"} onClick={() => { if (item === "Integrations") { window.location.assign("/integrations"); return; } if (item === "Pull requests") { window.location.assign("/pull-requests"); return; } setActive(item); notify(`Switched to ${item}`); }}><span>{[<CircleDot key="1" />, <GitPullRequest key="2" />, <Workflow key="3" />, <AlertTriangle key="4" />, <Settings2 key="5" />][index]}</span>{item}</button>)}</nav><hr /><div className="project"><strong>acme-platform</strong>12 repositories · 46 contributors</div><div className="project"><strong>Connected systems</strong>GitHub · Jira · Slack</div></aside>
    <main><header><div className="crumb">Workspace / <strong>{active}</strong> <span className={apiConnected ? "api-status connected" : apiConnected === false ? "api-status disconnected" : "api-status"}>{apiConnected ? "● API connected" : apiConnected === false ? "● API offline" : "● Connecting"}</span></div><div className="top-actions"><button onClick={() => notify("Search across code, decisions, incidents and docs")}><Search size={16} /></button><button onClick={() => notify("No new notifications")}><Activity size={16} /></button>{authState === "anonymous" && <a className="auth-button" href="/oauth2/authorization/github">Sign in</a>}<span className="avatar">AS</span></div></header><section className="content">
      <div className="hero"><div><h1>Good morning, Avnish</h1><p>Your engineering context is up to date across 12 repositories.</p></div><button className="primary" onClick={runVerification}><ShieldCheck size={16} />{running ? "Verifying…" : "Run verification"}</button></div>
      <div className="metrics"><Metric label="Open pull requests" value="24" note="↓ 18% from last week" /><Metric label="Context coverage" value="87%" note="↑ 6% this month" /><Metric label="Unverified AI changes" value="7" note="Needs attention" warn /><Metric label="Active incidents" value="2" note="Both assigned" /></div>
      <div className="grid"><Panel title="Pull request verification" action={<div className="tabs">{["All", "Attention"].map(item => <button key={item} className={filter === item ? "selected" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div>}><div className="pr-list">{prs.filter(pr => filter === "All" || pr.color !== "green").map(pr => <button className="pr" key={pr.title} onClick={() => setSelectedPr(pr)}><span className={`pr-icon ${pr.color}`}><pr.icon size={15} /></span><div><strong>{pr.title}</strong><small>{pr.meta}</small></div><span className={`status ${pr.color}`}>{pr.status}</span></button>)}</div></Panel><Panel title="AI change risk" muted="Last 30 days"><div className="risk"><div className="risk-score"><div className="ring"><b>36</b></div><div><strong>Moderate risk</strong><small>7 changes need human evidence before release.</small></div></div><Bar label="Tests added" value="78%" width="78%" /><Bar label="Docs updated" value="64%" width="64%" yellow /><Bar label="Rollback ready" value="91%" width="91%" /></div></Panel></div>
      <section className="panel automation"><PanelHead title="Automation opportunities" muted="Reduce repetitive work" /><div className="automation-grid"><Automation icon={<TestTube2 />} title="Flaky test quarantine" text="Group failures by signature and stop unreliable tests blocking releases." action="Review 12 tests" onClick={() => notify("Opening flaky test workspace…")} /><Automation icon={<Bot />} title="Incident triage" text="Correlate alerts, logs, deploys, and past incidents before paging a human." action="Simulate triage" onClick={() => notify("Incident triage simulation started…")} /><Automation icon={<Settings2 />} title="Environment drift" text="Find differences between local, staging, and production configuration." action="Scan environments" onClick={() => notify("Environment scan queued…")} /><Automation icon={<FileCheck2 />} title="Release readiness" text="Build one evidence checklist for engineering, QA, security, and DevOps." action="Open checklist" onClick={() => notify("Release checklist opened…")} /></div></section>
      <div className="bottom"><Panel title="Recent engineering memory" action={<button className="text-button" onClick={() => notify("Full engineering memory opened")}>View all <ChevronRight size={13} /></button>}><div className="events"><Event title="Decision: use async retries for payment webhooks" source="#payments-platform · linked to 4 pull requests" age="18m ago" /><Event title="Incident pattern detected in event-stream" source="Similar to INC-221 · suggested runbook attached" age="2h ago" /><Event title="Documentation drift found" source="auth-service README differs from current API behavior" age="Yesterday" /></div></Panel><Panel title="Estimated toil avoided" muted="This month"><div className="toil"><b>42h</b><div><strong>Recovered team time</strong><small>From automated triage, test grouping, and context search</small></div></div><Bar label="Test failures" value="18h" width="74%" /><Bar label="Incident context" value="14h" width="58%" /><Bar label="Release evidence" value="10h" width="42%" /></Panel></div>
    </section></main>{message && <div className="toast">{message}</div>}{selectedPr && <div className="overlay" onClick={() => setSelectedPr(null)}><aside className="detail-drawer" onClick={event => event.stopPropagation()}><div className="drawer-head"><div><span className={`status ${selectedPr.color}`}>{selectedPr.status}</span><h2>{selectedPr.title}</h2><small>{selectedPr.meta}</small></div><button className="close" onClick={() => setSelectedPr(null)}>×</button></div><div className="drawer-section"><h3>Verification summary</h3><p>{selectedPr.detail}. DevContext compared this change with repository history, engineering decisions, test results, and release requirements.</p></div><div className="drawer-section"><h3>Evidence findings</h3><Finding state="passed" text="Pull request has an assigned reviewer" /><Finding state={selectedPr.color === "green" ? "passed" : "attention"} text={selectedPr.color === "green" ? "Automated tests cover the changed behavior" : "Automated test evidence needs review"} /><Finding state={selectedPr.color === "red" ? "conflict" : "attention"} text={selectedPr.color === "red" ? "Conflicts with a previous engineering decision" : "Rollback procedure should be linked"} /></div><div className="drawer-section"><h3>Sources</h3><div className="source">GitHub pull request <span>→</span></div><div className="source">Related Jira ticket <span>→</span></div><div className="source">Engineering decision memory <span>→</span></div></div><button className="primary drawer-action" onClick={() => { setSelectedPr(null); notify("Review assigned to you"); }}>Assign review to me</button></aside></div>}
  </div>;
}

function Metric({ label, value, note, warn = false }: { label: string; value: string; note: string; warn?: boolean }) { return <div className="metric"><small>{label}</small><b>{value}</b><span className={warn ? "warn" : "positive"}>{note}</span></div>; }
function Panel({ title, muted, action, children }: { title: string; muted?: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="panel"><PanelHead title={title} muted={muted} action={action} />{children}</section>; }
function PanelHead({ title, muted, action }: { title: string; muted?: string; action?: React.ReactNode }) { return <div className="panel-head"><h2>{title}</h2>{action ?? <small>{muted}</small>}</div>; }
function Bar({ label, value, width, yellow = false }: { label: string; value: string; width: string; yellow?: boolean }) { return <div className="bar-row"><div><span>{label}</span><b>{value}</b></div><i className={yellow ? "yellow" : ""} style={{ width }} /></div>; }
function Automation({ icon, title, text, action, onClick }: { icon: React.ReactNode; title: string; text: string; action: string; onClick: () => void }) { return <div className="automation-card"><span className="automation-icon">{icon}</span><h3>{title}</h3><p>{text}</p><button onClick={onClick}>{action} <ChevronRight size={13} /></button></div>; }
function Event({ title, source, age }: { title: string; source: string; age: string }) { return <div className="event"><i /><div><strong>{title}</strong><small>{source}</small></div><time>{age}</time></div>; }
function Finding({ state, text }: { state: "passed" | "attention" | "conflict"; text: string }) { return <div className="finding"><span className={`finding-icon ${state}`}>{state === "passed" ? "✓" : state === "attention" ? "!" : "×"}</span><span>{text}</span><small>{state === "passed" ? "Evidence found" : state === "attention" ? "Review needed" : "Decision conflict"}</small></div>; }
