"use client";

import { FormEvent, useEffect, useState } from "react";
import { AlertTriangle } from "lucide-react";
import Link from "next/link";
import { apiFetch } from "../api";
import "./incidents.css";

type Workspace = { id: string; name: string };
type Incident = { id: string; title: string; severity: string; status: string; assignedTo?: string; updatedAt: string };

export default function IncidentsPage() {
  const [workspaces, setWorkspaces] = useState<Workspace[]>([]); const [workspaceId, setWorkspaceId] = useState("");
  const [incidents, setIncidents] = useState<Incident[]>([]); const [title, setTitle] = useState(""); const [severity, setSeverity] = useState("MEDIUM"); const [assignedTo, setAssignedTo] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { apiFetch("/api/workspaces").then(r => r.ok ? r.json() : Promise.reject()).then((items: Workspace[]) => { setWorkspaces(items); if (items[0]) setWorkspaceId(items[0].id); }).catch(() => setMessage("Sign in and create a workspace to manage incidents.")); }, []);
  useEffect(() => { if (!workspaceId) return; apiFetch(`/api/workspaces/${workspaceId}/incidents`).then(r => r.ok ? r.json() : Promise.reject()).then(setIncidents).catch(() => setMessage("Unable to load incidents.")); }, [workspaceId]);
  async function create(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); try { const response = await apiFetch(`/api/workspaces/${workspaceId}/incidents`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, severity, assignedTo: assignedTo || null }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to create incident"); setIncidents(items => [data, ...items]); setTitle(""); setAssignedTo(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create incident"); } finally { setSaving(false); } }
  async function updateStatus(id: string, status: string) { const response = await apiFetch(`/api/workspaces/${workspaceId}/incidents/${id}/status`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const data = await response.json(); if (response.ok) setIncidents(items => items.map(item => item.id === id ? data : item)); else setMessage(data.message || "Unable to update incident"); }
  return <main className="incidents-page"><div className="incidents-top"><Link href="/">← Back to dashboard</Link><span>DevContext</span></div><section className="incidents-card"><div className="incident-heading"><div><p className="eyebrow">Operational context</p><h1>Incidents</h1><p className="muted">Keep active incidents visible to engineering, QA, and DevOps in the selected workspace.</p></div><AlertTriangle size={30} /></div>{workspaces.length > 0 && <label className="workspace-select">Workspace<select value={workspaceId} onChange={event => setWorkspaceId(event.target.value)}>{workspaces.map(workspace => <option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</select></label>}<form onSubmit={create} className="incident-form"><input required maxLength={300} placeholder="Incident title" value={title} onChange={event => setTitle(event.target.value)} /><select value={severity} onChange={event => setSeverity(event.target.value)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select><input maxLength={320} placeholder="Assignee email (optional)" value={assignedTo} onChange={event => setAssignedTo(event.target.value)} /><button disabled={!workspaceId || saving}>{saving ? "Creating…" : "Create incident"}</button></form>{message && <p className="incident-message" role="alert">{message}</p>}<div className="incident-list">{incidents.length === 0 && !message && <p className="empty-state">No incidents recorded for this workspace.</p>}{incidents.map(incident => <article key={incident.id}><div><strong>{incident.title}</strong><small>{incident.severity} · {incident.status}{incident.assignedTo ? ` · ${incident.assignedTo}` : ""}</small></div><div className="incident-actions">{incident.status !== "ACKNOWLEDGED" && incident.status !== "RESOLVED" && <button onClick={() => updateStatus(incident.id, "ACKNOWLEDGED")}>Acknowledge</button>}{incident.status !== "RESOLVED" && <button onClick={() => updateStatus(incident.id, "RESOLVED")}>Resolve</button>}</div></article>)}</div></section></main>;
}
